# Generated by Django 4.2.7 on 2024-01-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='background_color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='text_color',
            field=models.CharField(max_length=30),
        ),
    ]
